#!/bin/bash
TIMEFORMAT=$'real\t%R\tuser\t%U\tsys\t%S'

for i in baseline with-static with-dynamic gprof; do
    echo $i
    for _ in {1..10}; do time ${1-build}/$i --no-threads &>/dev/null; done
done
